### PR TITLE
Fix phreeqc stream destruction

### LINKED ISSUE #161: Investigate why Phreeqc destructor is throwing an exception
I made a test to run PHREEQC  input script by file:
```
    std::string database_path = "W:/reaktoro_processing/DATABASE/phreeqc.dat";
    std::string input_path = "W:/reaktoro_processing/IN/IW.pqi";
    std::string output_path = "W:/reaktoro_processing/OUT/IW.pqo";
    
    Phreeqc phreeqc(database_path);
    phreeqc.execute(input_path, output_path);
```
After I ran it, the Phreeqc destructor threw an exception caused by a raw pointer (see the image below)

image

### PR DESCRIPTION
**Pull request by OtavioPellicano**
fixes #161

### CODE REVIEW

File: tests/IW [hunk 1]
```diff
@@ -0,0 +1,2 @@
+         sim	          pH	          pe	        temp	         Alk	     Acetate	          Ca	          Mg	          Na	          Cl	          Fe	        S(6)	       S(-2)
```
Comment (OtavioPellicano) [inline tests/IW:1]: these IW files were genereted automatically. Is there a way to don't do this?

File: Reaktoro/Interfaces/PhreeqcUtils.cpp [hunk 2]
```diff
@@ -62,8 +62,8 @@ auto execute(PHREEQC& phreeqc, std::string input, std::string output) -> void
     int errors = phreeqc.run_simulations();
     phreeqc.Get_phrq_io()->clear_istream();
 
-    // Delete the dynamically allocated stream objects
-    if(out != nullptr) delete out;
+    // Set nullptr to stream object (to avoid delete an already deleted pointer in Phreeqc destructor)
+    out = nullptr;
```
Comment (OtavioPellicano) [inline Reaktoro/Interfaces/PhreeqcUtils.cpp:66]: I tried to use shared_ptr<>, but it was not enough to solve the problem (it would be a little more tricky then we thought), so I decided to set `out` to `nullptr`. Just remove those lines work fine as well

File: thirdparty/phreeqc/utilities.cpp [hunk 3]
```diff
@@ -611,13 +611,13 @@ dup_print(const char *ptr, int emphasis)
 		for (i = 0; i < l; i++)
 			dash[i] = '-';
 		dash[i] = '\0';
-		output_msg(sformatf("%s\n%s\n%s\n\n", dash, save_in.c_str(), dash));
-		log_msg(sformatf("%s\n%s\n%s\n\n", dash, save_in.c_str(), dash));
+		output_msg(sformatf(u8"%s\n%s\n%s\n\n", dash, save_in.c_str(), dash));
```
Comment (OtavioPellicano) [inline thirdparty/phreeqc/utilities.cpp:614]: I changed to UTF-8 because the `pytest-file_regression` was not working with ANSI encode. As I reported in issue #162 , the output file is being saved with ANSI encode, even if inputs  file are UTF-8.

File: tests/IW (hunk 1 above)
Comment (tadeu) [reply tests/IW:1]: I don't know about the generation, but they probably shouldn't be committed? Perhaps add them to .gitignore?

File: tests/regression/test_phreeqc_execute/test_phreeqc_execute.txt [hunk 4]
```diff
@@ -0,0 +1,194 @@
...
+	Mg                5.165e-02   5.165e-02
+	Na                5.021e-01   5.021e-01
+	S(-2)             6.316e-03   6.316e-03
+	S(6)              2.551e-02   2.551e-02
+
+----------------------------Description of solution----------------------------
+
+                                       pH  =   6.884    
+                                       pe  =   4.000    
+      Specific Conductance (�S/cm,  25�C)  = 52878
```
Comment (tadeu) [inline tests/regression/test_phreeqc_execute/test_phreeqc_execute.txt:62]: It looks like it's not encoded in UTF-8

File: thirdparty/phreeqc/utilities.cpp (hunk 3 above)
Comment (tadeu) [reply thirdparty/phreeqc/utilities.cpp:614]: Hmm, `u8` won't make much difference here, it's the contents of `save_in` that should be encoded in UTF-8 already. The `u8` prefix will be useful only if the non-ASCII characters are directly inside the string, like `u8"°C"`, but in this case there are no non-ASCII characters _directly_ in the string.

File: tests/regression/test_phreeqc_execute/test_phreeqc_execute.txt (hunk 4 above)
Comment (OtavioPellicano) [reply tests/regression/test_phreeqc_execute/test_phreeqc_execute.txt]: I think now it is fixed

File: thirdparty/phreeqc/utilities.cpp (hunk 3 above)
Comment (allanleal) [reply thirdparty/phreeqc/utilities.cpp]: We need to be careful here because this is actual PHREEQC code - not Reaktoro. So, next time we update PHREEQC, this will be gone. The best would be to make such correction directly in their repository (or request this change there).

File: tests/IW (hunk 1 above)
Comment (allanleal) [reply tests/IW]: What about avoiding these output files altogether (which can potentially change based on the system, locale, the next version of PHREEQC, etc.)? We could just create a regression test based on the `ChemicalState` contents after executing the PHREEQC script file and creating the `ChemicalState` object containing the compositional state in the `Phreeqc` object. Would this suffice?

File: Reaktoro/Interfaces/PhreeqcUtils.cpp (hunk 2 above)
Comment (allanleal) [reply Reaktoro/Interfaces/PhreeqcUtils.cpp:66]: Would it be possible to have a test case that only checks the failure you were having before is gone (i.e., when performing `Phreeqc::execute` under some conditions)?

File: thirdparty/phreeqc/utilities.cpp (hunk 3 above)
Comment (tadeu) [reply thirdparty/phreeqc/utilities.cpp]: Good point, I hadn't realized that! Perhaps we should just define `NO_UTF8_ENCODING` then?

File: tests/IW (hunk 1 above)
Comment (OtavioPellicano) [reply tests/IW]: It sounds good, but I don´t know how to do that. could you please show me an example?

File: Reaktoro/Interfaces/PhreeqcUtils.cpp (hunk 2 above)
Comment (OtavioPellicano) [reply Reaktoro/Interfaces/PhreeqcUtils.cpp:66]: Actually I tried to do something like you said, for avoid by now the encoding error, but I did not realize how. Do you have any suggestion?

File: tests/IW (hunk 1 above)
Comment (allanleal) [reply tests/IW]: I think we don't even need the `ChemicalState`. We can use the methods available in [`Phreeqc`](https://reaktoro.org/cpp/classReaktoro_1_1Phreeqc.html) class to get the species amounts, temperature, pressure, activities, etc.

Comment (OtavioPellicano) [reply tests/IW]: I tried to get species amount, but the `IW` file was created. 
I just change the last two lines:
```
    p.execute(input_path)

    num_regression.check({'species_amount' : p.speciesAmounts()})
```

Comment (OtavioPellicano) [reply tests/IW]: we can also do not use regression at all, if you wish. Something like this:
```
    p.execute(input_path)

    assert approx(p.temperature()) == 298.15
    assert approx(p.pressure()) == 101324.99997084374
    assert approx(p.numElements()) == 11
    assert approx(p.numSpecies()) == 44
    assert approx(p.numPhases()) == 1
```

Comment (allanleal) [reply tests/IW]: That is even better indeed.

**Review by allanleal — APPROVED** [review]
Great, looks good!

**Review by tadeu — APPROVED** [review]
